##  -*-  coding: utf-8; mode: ruby -*-  ##
##  vi: set ft=ruby

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64-quantum"

  config.vm.provider "virtualbox" do |v|
    v.name   = "vagrant-ubuntu-quantum"
    v.memory = "2048"
  end

  config.vm.provision("file",
                      source: "../data",
                      destination: "~")
  config.vm.provision("root", type: "shell",
                      path: "provision.root.sh",
                      privileged: true)
  config.vm.provision("user", type: "shell",
                      path: "provision.user.sh",
                      privileged: false)

  config.vm.synced_folder("../share", "/vagrant", disabled: true)

end
