##  -*-  coding: utf-8; mode: ruby -*-  ##
##  vi: set ft=ruby

Vagrant.configure("2") do |config|
  config.vm.box = "takahiro-itou/ubuntu-bionic64-quantum"

  config.vm.provider "virtualbox" do |v|
    v.name   = "vagrant-ubuntu-quantum"
    v.memory = "2048"

    v.gui    = false
    v.customize [
      "modifyvm",           :id,
      "--cableconnected1",  "on",
      "--hwvirtex",         "on",
      "--nestedpaging",     "on",
      "--largepages",       "on",
      "--ioapic",           "on",
      "--pae",              "on",
      "--paravirtprovider", "kvm",
    ]
  end

  config.vm.boot_timeout = 900
  config.vm.network("private_network", ip: "192.168.33.98")

  config.vm.provision("file",
                      source: "../data",
                      destination: "/tmp/")

    config.vm.provision("file",
                        source: "~/VagrantConfig/",
                        destination: "/tmp/")

  config.vm.provision("root", type: "shell",
                      path: "provision.root.sh",
                      privileged: true)
  config.vm.provision("user", type: "shell",
                      path: "provision.user.sh",
                      privileged: false)
  config.vm.provision("hguser", type: "shell",
                      path: "provision.hguser.sh",
                      privileged: false)

  # config.vm.synced_folder("../share", "/vagrant", disabled: true)
  config.vm.synced_folder(".", "/vagrant", disabled: true)

end
